#!/bin/bash

# ------------
# A install script to install the public scripts.
#
# @author    Björn Hempel <bjoern@hempel.li>
# @date      2017-02-20
# @version   1.0
#
# @copyright ISC License
# @copyright
# @copyright Copyright (c) 2017, Björn Hempel
# @copyright
# @copyright Permission to use, copy, modify, and/or distribute this software for any
# @copyright purpose with or without fee is hereby granted, provided that the above
# @copyright copyright notice and this permission notice appear in all copies.
# @copyright
# @copyright THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# @copyright REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# @copyright AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# @copyright INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# @copyright LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
# @copyright OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# @copyright PERFORMANCE OF THIS SOFTWARE.
# @copyright
# @copyright Written by Björn Hempel <bjoern@hempel.li>.
# ------------

# some configs before
pathRoot="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# some includes
source "$pathRoot/lib/all"

# some constants
ROOT_UID="0"

# some configs
    installPath="/usr/local/bin"
declare -A installableApps
installableApps=([container]=sd-container [image]=sd-image)

# some configs after
sourcePath="$pathRoot/bin"

# check if we are root
if [ "$UID" -ne "$ROOT_UID" ]; then
    log "error" "You must be root to do that!"
    exit 1
fi

# install all given apps
for app in "${!installableApps[@]}"; do
    appTo="${installableApps[$app]}"

    installApp "$sourcePath/$app" "$installPath/$appTo"
done

exit 0
