#!/bin/bash



# ------------
# Check if docker image exists
#
# @author  Björn Hempel
# @version 1.0
# @date    2017-01-26
# ------------
dockerImageExists ()
{
    local imageName="$1"

    if [[ "$(docker images -q "$imageName" 2> /dev/null)" != "" ]]; then
        return 0
    fi

    return 1
}



# ------------
# Check if docker container is running
#
# @author  Björn Hempel
# @version 1.0
# @date    2017-01-22
# ------------
dockerContainerIsRunning() {
  if [[ "$(docker inspect -f {{.State.Running}} $1 2> /dev/null)" == "true" ]]; then
    return 0
  else
    return 1
  fi
}



# ------------
# Check if docker container exists (regardless whether it is running or not)
#
# @author  Björn Hempel
# @version 1.0
# @date    2017-01-22
# ------------
dockerContainerExists() {
  if [[ "$(docker inspect -f {{.State.Running}} $1 2> /dev/null)" == "" ]]; then
    return 1
  else
    return 0
  fi
}



# ------------
# Creates a new docker container
#
# @author  Björn Hempel
# @version 1.0
# @date    2017-01-26
# ------------
createContainer ()
{
    local containerName="$1"

    # some vars
    local          imageFile="$containerPath/image"
    local        linksFolder="$containerPath/links"
    local        portsFolder="$containerPath/ports"
    local      volumesFolder="$containerPath/volumes"
    local environmentsFolder="$containerPath/environments"
    local   parametersFolder="$containerPath/parameters"

    # check image link
    if [ ! -h "$imageFile" ]; then
        log 'error' "The image link \"$imageFile\" was not found." && exit 1
    else
        local imageLinkTarget=$(readlink -f "$imageFile")

        if [ "$imageLinkTarget" != "" ]; then
            local imageName=$(basename "$imageLinkTarget")
        else
            local imageName=$(readlink "$imageFile")
        fi
    fi

    # check ports
    declare -a ports
    if [ -d "$portsFolder" ]; then
        for fileSource in $(find "$portsFolder" -type l); do
            local fileTarget=$(readlink -f "$fileSource")

            local containerPort=$(basename "$fileSource")
            local      hostPort=$(basename "$fileTarget")

            ports[$containerPort]=$hostPort
        done
    fi

    # check volumes
    declare -A volumes
    if [ -d "$volumesFolder" ]; then
        for fileSource in $(find "$volumesFolder" -type l); do
            local volumesFolderSed=$(echo "$volumesFolder" | sed 's/\//\\\//g')
            local         hostPath=$(echo "$fileSource" | sed "s/$volumesFolderSed//g")
            if [ -e "$fileSource" ]; then
                local containerPath=$(readlink -f "$fileSource")
            else
                local containerPath=$(readlink "$fileSource")
            fi

            volumes[$containerPath]="$hostPath"
        done
    fi

    # check links
    declare -a links
    if [ -d "$linksFolder" ]; then
        for fileSource in $(find "$linksFolder" -type l); do
            local          linkFile=$(readlink -f "$fileSource")
            local linkContainerName=$(basename "$linkFile")

            links+=("$linkContainerName")
        done
    fi

    # check environments
    declare -A environments
    if [ -d "$environmentsFolder" ]; then
        for fileSource in $(find "$environmentsFolder" -type l); do
            local environmentFile=$(readlink -f "$fileSource")
            local environmentValue=$(basename "$environmentFile")
            local environmentName=$(basename "$fileSource")

            environments[$environmentName]="$environmentValue"
        done
    fi

    # check parameters
    declare -A parameters
    if [ -d "$parametersFolder" ]; then
        for fileSource in $(find "$parametersFolder" -type l); do
            local parameterFile=$(readlink -f "$fileSource")
            local parameterValue=$(basename "$parameterFile")
            local parameterName=$(basename "$fileSource")

            parameters[$parameterName]="$parameterValue"
        done
    fi

    local command="docker run -dit"

    # add ports to command
    for containerPort in "${!ports[@]}"; do
        local hostPort=${ports[$containerPort]}

        command="$command -p $containerPort:$hostPort"
    done

    # add volume to command
    for containerPath in "${!volumes[@]}"; do
        local hostPath=${volumes[$containerPath]}

        command="$command -v $containerPath:$hostPath"
    done

    # add environments to command
    for environmentName in "${!environments[@]}"; do
        local environmentValue=${environments[$environmentName]}

        command="$command -e \"$environmentName=$environmentValue\"" #"
    done

    # add parameters to command
    for parameterName in "${!parameters[@]}"; do
        local parameterValue=${parameters[$parameterName]}

        if [ "${parameterValue:0:1}" != "=" ]; then
            parameterValue=" $parameterValue"
        fi

        command="$command --$parameterName$parameterValue"
    done

    # show links
    for linkContainerName in "${links[@]}"; do
        command="$command --link $linkContainerName:$linkContainerName"
    done

    # add containerName
    command="$command --name $containerName"

    # add image parameter
    command="$command $imageName"

    if $DEBUG; then
        echo "Command to execute:"
        echo "$command"
        exit
    else
        echo 'do it'
        exit

        # eval command
        local resultCommand=$(eval "$command")
    fi
}



# ------------
# Start a new docker container
#
# @author  Björn Hempel
# @version 1.0
# @date    2017-01-26
# ------------
startContainer ()
{
    local containerName="$1"
    local returnCommand=$(docker start "$containerName")
}



# ------------
# Unpause a new docker container
#
# @author  Björn Hempel
# @version 1.0
# @date    2017-01-26
# ------------
unpauseContainer ()
{
    local containerName="$1"
    local returnCommand=$(docker unpause "$containerName")
}



# ------------
# Stop a new docker container
#
# @author  Björn Hempel
# @version 1.0
# @date    2017-01-26
# ------------
stopContainer ()
{
    local containerName="$1"
    local returnCommand=$(docker stop "$containerName")
}



